### ISSUE TITLE
OnErrorNotImplementedException: Invalid column name

### ISSUE THREAD

**Issue by GuilhE** [Doctoror/RxCursorLoader#1]
I have this query:
```
private RxCursorLoader.Query mPlaylistQuery = new RxCursorLoader.Query.Builder()
            .setContentUri(Uri.parse("content://com.google.android.music.MusicContent/playlists")/*MediaStore.Audio.Playlists.EXTERNAL_CONTENT_URI*/)
            .setProjection(new String[]{
                    MediaStore.Audio.Playlists._ID,
                    MediaStore.Audio.Playlists.NAME,
                    MediaStore.Audio.Playlists.DATE_ADDED,
            })
            .setSortOrder(MediaStore.Audio.Playlists.NAME)
            .create();
```
and then
```
RxCursorLoader
                .create(mContentResolver, query)
                .map(cursor -> {...
```

But I'm getting this stacktrace:

> FATAL EXCEPTION: main
>                                                                 Process: com.tivoli.dev, PID: 19922
>                                                                 io.reactivex.exceptions.OnErrorNotImplementedException: Invalid column name
>                                                                     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
>                                                                     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
>                                                                     at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:45)
>                                                                     at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
>                                                                     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
>                                                                     at android.os.Handler.handleCallback(Handler.java:751)
>                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                     at android.os.Looper.loop(Looper.java:154)
>                                                                     at android.app.ActivityThread.main(ActivityThread.java:6123)
>                                                                     at java.lang.reflect.Method.invoke(Native Method)
>                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
>                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
>                                                                  Caused by: java.lang.IllegalArgumentException: Invalid column name
>                                                                     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
>                                                                     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
>                                                                     at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
>                                                                     at android.content.ContentResolver.query(ContentResolver.java:530)
>                                                                     at android.content.ContentResolver.query(ContentResolver.java:472)
>                                                                     at com.doctoror.rxcursorloader.RxCursorLoader$CursorLoaderOnSubscribe.reload(RxCursorLoader.java:207)
>                                                                     at com.doctoror.rxcursorloader.RxCursorLoader$CursorLoaderOnSubscribe.subscribe(RxCursorLoader.java:183)
>                                                                     at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
>                                                                     at io.reactivex.Observable.subscribe(Observable.java:10901)
>                                                                     at io.reactivex.internal.operators.observable.ObservableDoOnLifecycle.subscribeActual(ObservableDoOnLifecycle.java:33)
>                                                                     at io.reactivex.Observable.subscribe(Observable.java:10901)
>                                                                     at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
>                                                                     at io.reactivex.Observable.subscribe(Observable.java:10901)
>                                                                     at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
>                                                                     at io.reactivex.Observable.subscribe(Observable.java:10901)
>                                                                     at io.reactivex.internal.operators.observable.ObservableElementAtSingle.subscribeActual(ObservableElementAtSingle.java:37)
>                                                                     at io.reactivex.Single.subscribe(Single.java:2700)
>                                                                     at io.reactivex.internal.operators.single.SingleDoOnSubscribe.subscribeActual(SingleDoOnSubscribe.java:41)
>                                                                     at io.reactivex.Single.subscribe(Single.java:2700)
>                                                                     at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
>                                                                     at io.reactivex.Single.subscribe(Single.java:2700)
>                                                                     at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
>                                                                     at io.reactivex.Single.subscribe(Single.java:2700)
>                                                                     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
>                                                                     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
>                                                                     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
>                                                                     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
>                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
>                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>                                                                     at java.lang.Thread.run(Thread.java:761)

But it works when used like this:
```
Cursor playlists = context.getContentResolver().query(Uri.parse("content://com.google.android.music.MusicContent/playlists"), new String[]{
                    MediaStore.Audio.Playlists._ID,
                    MediaStore.Audio.Playlists.NAME,
                    MediaStore.Audio.Playlists.DATE_ADDED,
            }}, null, null, null); 

```
Do you know what could might be causing this?
Thanks for your time.

**Comment by Doctoror** [comment]
Hello, GuilhE. I see in first case you pass the sort order and in second case there is no sort order in query. Could the sort order cause the issues? What happens of you include the sort order to the second query?

**Comment by GuilhE** [comment]
I run a few tests and the problem is in the projection configuration and not in your lib.
Sorry ^^

**Comment by Doctoror** [comment]
Np, thanks for the final feedback!
