### ISSUE TITLE
can't import 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Doctoror/RxCursorLoader#2]
Got this:

![image](https://user-images.githubusercontent.com/5357526/32222891-b63671a2-be43-11e7-935a-697cde43672e.png)

Updating everything to latest version didn't help.

**Comment by Doctoror** [comment]
Seems like it's not configured for Gradle plugin 3.0.0 or later. I will update this today later.

**Comment by AndroidDeveloperLB** [comment]
But I tried to update it too, even to the new alpha version:

![image](https://user-images.githubusercontent.com/5357526/32223276-6087c9d4-be45-11e7-9618-b8300e575c61.png)

**Comment by Doctoror** [comment]
I can't tell what's going on until I get my hands on it. I will take a look later.

**Comment by AndroidDeveloperLB** [comment]
Thank you for the quick reply. You are great

**Comment by Doctoror** [comment]
NP. Thanks.
Added support for Gradle plugin 3.0.0.

**Comment by AndroidDeveloperLB** [comment]
Seems to work fine now.
The style looks like of Gingerbread though.

**Comment by Doctoror** [comment]
It's because I did not include `appcompat` or any fancy themes for the demo app to keep it slim.
You can override and to set material theme in `values-v21`, but it's not worth for the demo as the demo only shows how to use the API.

**Comment by AndroidDeveloperLB** [comment]
Not an issue. Just weird that you didn't use it. Can make your demo more modern this way.
The demo is the way to show your library to the world. Sure it doesn't have to show everything, but at least have it look good.
Just my opinion...

**Comment by Doctoror** [comment]
To avoid including `appcompat`, I will update to use `Holo` for `v11` and `Material` for `v21` later.

**Comment by AndroidDeveloperLB** [comment]
The demo can include the appcompat. The library doesn't have to.
It's very common to see it this way on other repos.

**Comment by Doctoror** [comment]
I still don't like this idea of adding yet one more dependency just to show a list of media.

**Comment by AndroidDeveloperLB** [comment]
For the very minimal UI, you could even show it all on the logs...
But this is a demo. It should look well.
A dependency to the demo doesn't mean that us the developers will use it too. It's only for the demo. What we use is in the library itself.
In a similar manner, your demo uses the storage permission. It didn't have to do it. It could instead simulate loading of them, and provide fake results. You used something that you don't have to, just for the demo.
In fact, maybe it's not a good example, because I actually preferred if you didn't use this permission, as I got only a single item the demo shows. Quite empty...

**Comment by Doctoror** [comment]
True, it would be better to bundle the ContentProvider in a demo app, maybe I should really do it.
But making the demo larger just to see an `appcompat` theme running on old device isn't worth it.

**Comment by AndroidDeveloperLB** [comment]
Material design is a thing. You should follow it. It's also not hard to use.

**Comment by Doctoror** [comment]
I disagree adding appcompat just for a demo. I will make it use Material theme in `styles-v21`, otherwise let it use fallback.

**Comment by AndroidDeveloperLB** [comment]
You can check every other library's demo. There is no need to fear from adding it. Google recommends using the support library all the time, even if your app already has what it takes to use this style.

**Comment by Doctoror** [comment]
It will increase compilation time for no good reason. This is not a production app, this is just a one-Activity demo, and this is the perfect case to use a platform theme. This is not even a UI library, there is no reason to add a big dependency to make it appealing in old devices.

**Comment by AndroidDeveloperLB** [comment]
Compilation time for demo app is not something to worry about (and it's not a long time too). If it was in the library, it would make more sense to think about it, especially because as you said, it's not a UI library.
The library won't be affected by adding a dependency to the demo. It's just a demo.

**Comment by Doctoror** [comment]
Of course it won't. I like it when there are minimum dependencies and this one just don't make a perfect sense for me. Anyway, if I made it use a platform Material theme in first place, you wouldn't even notice because you would probably run on a post-Lollipop device.

**Comment by AndroidDeveloperLB** [comment]
Practically every modern app you will download nowadays, will have about the same material design used form the support library, one way or another, even on old Android versions.
It's not that hard to add it as you think.

**Comment by AndroidDeveloperLB** [comment]
Even when you create a new project on the IDE, by default it enables the support library, and that's even if you have minSdk very high.

**Comment by Doctoror** [comment]
Because most projects need it and also this allows newbies to get along with it out of the box.
However this is not the case the `appcompat` should be used.

Also some stuff like `support-design` require `appcompat` theme, so that's the reason to use it even if you have high min sdk. However, again, this demo does not need it.

**Comment by AndroidDeveloperLB** [comment]
You choice. To me, when I see a sample that looks like it, I immediately label it (in my thoughts) as "old", "not updated", "obsolete", "deprecated"... Something that the developer didn't make the minimal effort into it to look well and modern. A project that the developer probably left behind and will never update again. Something is not right.
It's not using FAB vs ActionBar item. It's the much more basic than it. 
It's not expected to see such a thing nowadays for new projects. The style isn't even Holo. Gingerbread isn't supported anymore by Google on many aspects, including the support library itself.

Also, as I wrote, the demo also doesn't need permissions. It could have used fake data instead, and it would even be better, because not all of us have anything to show for it. For some, the list would have been empty, so the demo would show nothing special is going on...

Another alternative, which is more common thing to show, is contacts. Most users have contacts in the address book.

**Comment by Doctoror** [comment]
Regarding the permissions, I just noticed that the library has the storage permissions, which it shouldn't. It's a bug. I'm also updating the demo to use fake provider. Will update master soon.

**Comment by AndroidDeveloperLB** [comment]
Please also use material design.

**Comment by Doctoror** [comment]
Updated with changes:
- use platform Holo and Material theme
- use bundled ContentProvider for demo and tests
- remove storage permissions from library

Version 2.0.1 is released to Maven and will be available as soon as repos synced.
