### ISSUE TITLE
Min API 26

### ISSUE THREAD

**Issue by eygraber** [Doctoror/RxCursorLoader#3]
After updating to 2.0.1 I get a build error that says I need at least a min API of 26

> Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process /home/me/.gradle/caches/transforms-1/files-1.1/library-2.0.1.aar/3784decf3c12aa7c2d88d1648a1349f4/jars/classes.jar

> Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing com/doctoror/rxcursorloader/RxCursorLoader.class
Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)

> Error:Execution failed for task ':app:transformClassesWithDexBuilderForDevDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /home/me/.gradle/caches/transforms-1/files-1.1/library-2.0.1.aar/3784decf3c12aa7c2d88d1648a1349f4/jars/classes.jar

**Comment by Doctoror** [comment]
It's because the library uses Java 8. Please add the following to the `android` block of the modules that depend on RxCusorLoader:
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by eygraber** [comment]
Doesn't this come with a compile time performance hit because desugar gets turned on?

**Comment by Doctoror** [comment]
I've never measured it. Though obligating clients to use Java 8 features is not the best option, especially considering that we have Kotlin now. I will introduce a new version with java 8 removed this week

**Comment by Doctoror** [comment]
@eygraber version 2.0.2 with Java 7 released and will be available soon as Nexus repository syncs.
